### ISSUE TITLE
AttributeError while saving in @@personal-information view

### ISSUE THREAD

**Issue by verena-rh** [plone/plone.app.users#126]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

In the @@personal-information view I get the following error when I make changes but the portrait image remains the same:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 181, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 391, in publish_module
  Module ZPublisher.WSGIPublisher, line 285, in publish
  Module ZPublisher.mapply, line 98, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module plone.app.users.browser.userdatapanel, line 92, in __call__
  Module z3c.form.form, line 233, in __call__
  Module plone.z3cform.fieldsets.extensible, line 62, in update
  Module plone.z3cform.patch, line 31, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 301, in __call__
  Module z3c.form.button, line 159, in __call__
  Module plone.app.users.browser.account, line 299, in handleSave
  Module plone.app.users.browser.account, line 276, in validate_portrait
AttributeError: 'NOT_CHANGED' object has no attribute 'open'
```

### What I did:

Added an portrait and saved. Then edit again, leave the portrait unchanged and save.

### What I expect to happen:

The changes are saved.

### What actually happened:

Get the above error message.

### What version of Plone/ Addons I am using:
Plone 6.0.11.1 Classic
plone.app.users 3.0.6

**Comment by mauritsvanrees** [comment]
Confirmed.  This is caused by PR #123.  Workaround is to switch back to `plone.app.users` 3.0.5.
I am working on a proper fix.

**Comment by mauritsvanrees** [comment]
I have released `plone.app.users` 3.0.7 with the fix.
